name: 'Sync github issues to jira'
inputs:
  JIRA_URL:
    description: Jira URL domain to be stored as a secret.
    required: true
  JIRA_USERNAME:
    description: Jira username to be stored as a secret.
    required: true
  JIRA_API_TOKEN:
    description: Jira API token to be stored as a secret.
    required: true
  JIRA_COMPONENT:
    description: Jira component to be stored as a secret.
    required: true
  JIRA_PROJECT_KEY:
    description: Jira project key to be stored as a secret.
    required: true
  JIRA_EPIC_KEY:
    description: Jira epic key to be stored as a secret.
    required: true
  JIRA_ISSUE_TYPE:
    description: Jira issue type.
    required: false
    default: "Feature"
  JIRA_LINK_TYPE:
    description: Jira link type.
    required: false
    default: "Dependency"
  label:
    description: 'Label which will trigger a Jira import.'
    required: true
    default: 'jira'

runs:
  using: "composite"
  steps:
    #- name: Dump GitHub context
    #  run: echo '${{ toJSON(github) }}'
    #  shell: bash
    - name: restrict action to labelled issues and issue comments
      shell: bash
      run: |
        set -eux
        
        echo "NeedsJiraUpdate=false" >> $GITHUB_ENV

        if [ ${{ github.event_name }} != "issues" ] && [ ${{ github.event_name }} != "issue_comment" ]; then
          echo "This action only work on issue events. Please use on: issues or issue_comment to use this action."
          exit 1
        fi

        if [ ${{ github.event.issue.pull_request }} ]; then
          echo "This action only work on issues, not pull requests."
          exit 0
        fi

        # Issue creation with label will trigger 2 events and run twice: one create, one labelled.
        # let just focus on labelling then for creating issues Jira-side.
        if [ ${{ github.event_name }} == "issues" ] && [ ${{ github.event.action }} == "opened" ]; then
          echo "Ignoring creation of issues as a label will trigger a second event."
          exit 0
        fi

        # We only operate on labelled issues or issues that are just unlabeled with our desired label
        ## check if one label of labels is our jira label
        toconsider=${{ contains(github.event.issue.labels.*.name, inputs.label) }}
        ## second chance, this has just been unlabeled and needs to be deleted on Jira
        if [ ${{ github.event.action }} == "unlabeled" ] && [ ${{ github.event.label.name }} == ${{ inputs.label }} ]; then
          toconsider=true
        fi
        if [ "${toconsider}" == false ]; then
          echo "Our desired label not found on issue or not unlabeled, skipping"
          exit 0
        fi

        # And finally, for the "labeled" event, we are only interested if the new added label is our desired one.
        if [ ${{ github.event.action }} == "labeled" ] && [ ${{ github.event.label.name }} != ${{ inputs.label }} ]; then
          echo "Not interested in this action, skipping"
          exit 0
        fi

        # last one wins
        echo "NeedsJiraUpdate=true" >> $GITHUB_ENV

    - name: Remove specific label from issue
      if: ${{ env.NeedsJiraUpdate == 'true' }}
      uses: actions/github-script@v7
      with:
        script: |
          const labelToRemove = ${{ inputs.label }};
          const { owner, repo } = context.repo;
          const issue_number = context.issue.number;
          
          // Remove the label
          await github.issues.removeLabel({
            owner,
            repo,
            issue_number,
            name: labelToRemove
          });
          console.log(`Label "${labelToRemove}" removed from issue

    - name: "Convert markdown to jira"
      if: ${{ env.NeedsJiraUpdate == 'true' }}
      id: convert_markdown
      shell: bash
      run: |
        set -eux
        
        # Install markdown to jira converter
        sudo apt update
        sudo apt install -y python3
        pip3 install mistletoe
        
        # Convert mardown to jira.
        TMPDIR=$(mktemp -d)
        trap 'rm -rf -- "$TMPDIR"' EXIT
        echo "${{ github.event.issue.body }}" > $TMPDIR/body.md
        description=$(mistletoe $TMPDIR/body.md --renderer mistletoe.contrib.jira_renderer.JiraRenderer)
        echo "description=${description}" >> $GITHUB_OUTPUT    

    - name: "Update jira"
      if: ${{ env.NeedsJiraUpdate == 'true' }}
      id: update_jira
      shell: bash
      env:
        JIRA_USERNAME: '${{ inputs.JIRA_USERNAME }}'
        JIRA_API_TOKEN: '${{ inputs.JIRA_API_TOKEN }}'
        JIRA_AUTHORIZATION: '${{ inputs.JIRA_AUTHORIZATION }}'
      run: |
        set -eu
        
        if [ -z "$JIRA_AUTHORIZATION" ]; then
          jira_auth=$(echo -n "${JIRA_USERNAME}:${JIRA_API_TOKEN}" | base64 | tr -d '\n')
        else
          jira_auth="${JIRA_AUTHORIZATION}"
        fi
        
        jira_auth_header="Authorization: Basic $jira_auth"

        echo "Creating issue ${{ github.event.issue.title }} and linking it as a dependency to ${{ inputs.DEPENDENT_ISSUE }}"
        create_body='{
          "fields": {
            "project": {
              "key": "${{ inputs.JIRA_PROJECT_KEY }}"
            },
            "summary": "${{ github.event.issue.title }}",
            "description": "${{ steps.convert_markdown.outputs.description }}",
            "issuetype": {
              "name": "${{ inputs.JIRA_ISSUE_TYPE }}"
            },
            "customfield_15140": "${{ inputs.JIRA_EPIC_KEY }}",
            "components": [
              {
                "name": "${{ inputs.JIRA_COMPONENT }}"
              }
            ]
          }
        }'
        
        # Extract the new issue key from the response
        create_response=$(curl -H "$jira_auth_header" -X POST -H "Content-Type: application/json" --data "${create_body}" "${{ inputs.JIRA_URL }}/rest/api/2/issue/")
        new_issue_key=$(echo $create_response | jq -r '.key')
        echo "jira_issue_key=${new_issue_key}" >> $GITHUB_OUTPUT    
        echo "created new issue in Jira: ${new_issue_key}"

        # Link the new issue to the github issue.
        echo "Linking Jira issue to GitHub issue"
        gh_link_body='{
          "object": {
            "url" : "${{ github.event.issue.html_url }}",
            "title" : "GitHub Issue"
          }
        }'
        curl --silent -o /dev/null -w "%{http_code}" -H "$jira_auth_header" -X POST -H "Content-Type: application/json" --data "${gh_link_body}" "https://${{ inputs.JIRA_URL }}/rest/api/2/issue/${new_issue_key}/remotelink"
        echo "Linked ${new_issue_key} to GitHub issue ${{ github.event.issue.number }}"
        
        echo "Linking Jira issue to epic"
        epic_link_body='{
          "type": {
            "name": "${{ inputs.JIRA_LINK_TYPE }}"
          },
          "inwardIssue": {
            "key": "${{ inputs.JIRA_EPIC_KEY }}"
          },
          "outwardIssue": {
            "key": "$new_issue_key"
          }
        }'
        curl --silent -o /dev/null -w "%{http_code}" -H "$jira_auth_header" -X POST -H "Content-Type: application/json" --data "${epic_link_body}" "https://${{ inputs.JIRA_URL }}/rest/api/2/issuelink"

    - name: Remove specific label from issue
      shell: bash
      run: |
        LABEL_TO_REMOVE="${{ inputs.label }}"
        ISSUE_NUMBER=${{ github.event.issue.number }}
        OWNER=${{ github.repository_owner }}
        REPO=${{ github.event.repository.name }}
        
        echo "Removing label ${LABEL_TO_REMOVE} from issue ${ISSUE_NUMBER}"
        curl -s -X DELETE \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/$OWNER/$REPO/issues/$ISSUE_NUMBER/labels/$LABEL_TO_REMOVE
